### ISSUE TITLE
The 'API docs' web page does not redirect correctly generating a 404 status code

### ISSUE THREAD

**Issue by tumael** [jasp402/js-packtools#24]
Look at the steps below:

1. Go to url: "https://github.com/jasp402/js-packtools".
2. Go to section "List of Content".
3. Click on "API Doc".

Actual result: The web page is displaying "404 - Not found".
Expected result: See the "API Documentation" web page.

**Comment by jasp402** [comment]
Fixed broken link error.
Verify [version 0.10.5](https://www.npmjs.com/package/js-packtools)

**Comment by jasp402** [comment]
Please confirm if the issue has been resolved!
